# Generated by Django 5.0.7 on 2024-07-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mualif', models.SmallIntegerField()),
                ('janr', models.CharField(max_length=10)),
                ('beti', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.SmallIntegerField()),
                ('userNAME', models.CharField(max_length=30)),
                ('password', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('t_yili', models.SmallIntegerField()),
                ('trik', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('h_raqami', models.SmallIntegerField()),
                ('sinf', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ism',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olgan_sana', models.DateField()),
                ('qaytarish_sana', models.DateField()),
                ('qaytardimi', models.BooleanField()),
                ('kitob_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kitob')),
                ('kutubxonachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kutubxonachi')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.oquvchi')),
            ],
        ),
    ]
