# Generated by Django 5.0.7 on 2024-08-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_kitob_kutubxonachi_muallif_oquvchi_alter_user_ism_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
